/*
This file holds all the actions name
that will be used by reducers and other action files.
*/

// modal
export const OPEN_REMOVE_USER_CONFIRM_MODAL = 'OPEN_REMOVE_USER_CONFIRM_MODAL';
export const DISMISS_REMOVE_USER_CONFIRM_MODAL =
  'DISMISS_REMOVE_USER_CONFIRM_MODAL';

// next presenters
export const BROWNBAG_NEXT_PRESENTER = 'BROWNBAG_NEXT_PRESENTER';
export const BROWNBAG_NEXT_PRESENTER_SUCCESS =
  'BROWNBAG_NEXT_PRESENTER_SUCCESS';

// potential candidates
export const LOAD_POTENTIAL_USERS_SUCCESS = 'LOAD_POTENTIAL_USERS_SUCCESS';
export const RECEIVE_POTENTIAL_USERS = 'RECEIVE_POTENTIAL_USERS';
export const REQUEST_POTENTIAL_USERS = 'REQUEST_POTENTIAL_USERS';
export const RECEIVE_POTENTIAL_USERS_SUCCESS =
  'RECEIVE_POTENTIAL_USERS_SUCCESS';
export const RECEIVE_POTENTIAL_USERS_FAILURE =
  'RECEIVE_POTENTIAL_USERS_FAILURE';

// shuffle
export const REQUEST_BROWNBAG_SHUFFLE = 'REQUEST_BROWNBAG_SHUFFLE';
export const RECEIVE_BROWNBAG_SHUFFLE_SUCCESS =
  'RECEIVE_BROWNBAG_SHUFFLE_SUCCESS';

// confirm or cancel brownBag
export const CONFIRM_BROWNBAG_DONE = 'CONFIRM_BROWNBAG_DONE';
export const CONFIRM_BROWNBAG_CANCEL = 'CONFIRM_BROWNBAG_CANCEL';
export const BROWNBAG_ACTION_ERROR = 'BROWNBAG_ACTION_ERROR';

// log in
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST_FAIL = 'LOGIN_REQUEST_FAIL';

//log out
export const LOG_OUT_REQUEST_SUCCESS = 'LOG_OUT_REQUEST_SUCCESS';
